# Generated by Django 5.1 on 2024-08-29 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.CharField(choices=[('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('Suite Room', 'Suite Room')], default='Double Room', max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('room_area', models.CharField(max_length=100)),
                ('number_of_guests', models.IntegerField()),
                ('price', models.IntegerField()),
                ('connecting_rooms', models.IntegerField()),
                ('no_of_bed', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tag', models.CharField(blank=True, choices=[('Best Seller', 'Best Seller'), ('Popular', 'Popular')], max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='room')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='home.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
